"""Run PC2 end-to-end (deep training with transfer learning + explicit fine-tuning).

This script is the reproducible entrypoint for PC2:
- runs a deep classification training with a frozen-warmup phase then unfreezes
- snapshots small, versionable artifacts under output/etapa2/

The source of truth for metrics remains output/training_experiments.json.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import subprocess
import sys
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[2]
OUTPUT_DIR = REPO_ROOT / "output"
ETAPA2_DIR = OUTPUT_DIR / "etapa2"


def _sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def _read_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def _git_commit() -> str:
    try:
        out = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=REPO_ROOT)
        return out.decode("utf-8").strip()
    except Exception:
        return "unknown"


def _git_is_dirty() -> bool:
    try:
        out = subprocess.check_output(["git", "status", "--porcelain"], cwd=REPO_ROOT)
        return bool(out.strip())
    except Exception:
        return True


def _relativize_cmd(cmd: list[str]) -> list[str]:
    """Make the command portable by avoiding machine-specific absolute paths."""
    display: list[str] = []
    for raw in cmd:
        try:
            p = Path(raw)
        except Exception:
            display.append(raw)
            continue

        if not p.is_absolute():
            display.append(raw)
            continue

        try:
            display.append(str(p.relative_to(REPO_ROOT)))
        except Exception:
            display.append(p.name)
    return display


def _latest_pc2_entry(entries: list[dict[str, Any]], *, scenario: str) -> dict[str, Any]:
    matches = [e for e in entries if str(e.get("scenario", "")) == scenario]
    if not matches:
        raise SystemExit(
            f"PC2 entry not found in output/training_experiments.json (scenario={scenario})."
        )
    # timestamps are stored as strings "YYYY-MM-DD HH:MM:SS"; lexicographic works.
    return sorted(matches, key=lambda e: str(e.get("timestamp", "")))[-1]


def _write_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def _copy_plot(src: Path, dst: Path) -> None:
    if not src.exists():
        raise SystemExit(f"Missing plot generated by pipeline: {src}")
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_bytes(src.read_bytes())


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Run PC2 (transfer learning + explicit fine-tuning) and snapshot etapa2 artifacts."
    )
    parser.add_argument("--backbone", default="efficientnet", choices=["efficientnet", "medicalnet", "densenet"])
    parser.add_argument("--epochs", type=int, default=6)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--multimodal", action="store_true", help="Enable multimodal fusion (USE_MULTIMODAL=1).")
    parser.add_argument(
        "--warmup-epochs",
        type=int,
        default=2,
        help="Number of frozen epochs before unfreezing encoders (RESNET_WARMUP_EPOCHS).",
    )
    parser.add_argument(
        "--deep-scenario",
        type=str,
        default="pc2_finetune",
        help="Scenario prefix saved into output/training_experiments.json (DEEP_SCENARIO).",
    )
    parser.add_argument(
        "--skip-train",
        action="store_true",
        help="Do not run training; only snapshot artifacts from the latest matching history entry.",
    )
    args = parser.parse_args()

    OUTPUT_DIR.mkdir(exist_ok=True)
    ETAPA2_DIR.mkdir(parents=True, exist_ok=True)

    split_csv = OUTPUT_DIR / "exam_level_dataset_split.csv"
    if not split_csv.exists():
        raise SystemExit(
            f"Missing official split CSV: {split_csv}. Run: python3 run_baselines_cli.py"
        )

    # Explicit PC2 contract: transfer learning + frozen warmup + unfreeze.
    os.environ["RESNET_SEED"] = str(int(args.seed))
    os.environ["DEEP_SCENARIO"] = str(args.deep_scenario)
    os.environ["RESNET_FREEZE"] = "1"
    os.environ["RESNET_WARMUP_EPOCHS"] = str(int(args.warmup_epochs))
    os.environ["USE_MULTIMODAL"] = "1" if args.multimodal else "0"

    python_exe = REPO_ROOT / ".venv" / "bin" / "python"
    if not python_exe.exists():
        python_exe = Path(sys.executable)

    cmd = [
        str(python_exe),
        str(REPO_ROOT / "run_deep_models_cli.py"),
        "--seed",
        str(int(args.seed)),
        "--epochs",
        str(int(args.epochs)),
        "--backbones",
        str(args.backbone),
    ]
    if args.multimodal:
        cmd.append("--multimodal")

    if not args.skip_train:
        print("[PC2] Running:")
        print(" ".join(cmd))
        subprocess.run(cmd, cwd=REPO_ROOT, check=True)

    experiments_path = OUTPUT_DIR / "training_experiments.json"
    if not experiments_path.exists():
        raise SystemExit(f"Missing training history file: {experiments_path}")
    entries = _read_json(experiments_path)
    if not isinstance(entries, list):
        raise SystemExit("training_experiments.json must be a list of experiments")

    expected_scenario = f"{args.deep_scenario}_{args.backbone}_classification_seed{int(args.seed)}"
    entry = _latest_pc2_entry(entries, scenario=expected_scenario)

    metrics = {
        "scenario": expected_scenario,
        "timestamp": entry.get("timestamp"),
        "model": entry.get("model"),
        "seed": entry.get("seed"),
        "split_csv_sha256": entry.get("split_csv_sha256"),
        "pretrained": entry.get("pretrained"),
        "freeze_backbone_initial": entry.get("freeze_backbone_initial"),
        "freeze_warmup_epochs": entry.get("freeze_warmup_epochs"),
        "unfreeze_epoch": entry.get("unfreeze_epoch"),
        "trainable_params_initial": entry.get("trainable_params_initial"),
        "trainable_params_after_unfreeze": entry.get("trainable_params_after_unfreeze"),
        "epochs": entry.get("epochs"),
        "test_accuracy": entry.get("test_accuracy"),
        "test_precision": entry.get("test_precision"),
        "test_recall": entry.get("test_recall"),
        "test_f1": entry.get("test_f1"),
        "test_confusion_matrix": entry.get("test_confusion_matrix"),
    }
    _write_json(ETAPA2_DIR / "metrics.json", metrics)

    # Copy small plots into the stage snapshot with stable names.
    src_curves = OUTPUT_DIR / f"{args.backbone}_classification_learning_curves.png"
    src_cm = OUTPUT_DIR / f"confusion_{args.backbone}_classification.png"
    dst_curves = ETAPA2_DIR / "plots" / f"{args.backbone}_pc2_learning_curves.png"
    dst_cm = ETAPA2_DIR / "plots" / f"{args.backbone}_pc2_confusion_matrix.png"
    _copy_plot(src_curves, dst_curves)
    _copy_plot(src_cm, dst_cm)

    manifest = {
        "pc": "PC2",
        "git_commit": _git_commit(),
        "git_dirty": _git_is_dirty(),
        "command": _relativize_cmd(cmd),
        "env": {
            "DEEP_SCENARIO": os.environ.get("DEEP_SCENARIO"),
            "RESNET_SEED": os.environ.get("RESNET_SEED"),
            "RESNET_FREEZE": os.environ.get("RESNET_FREEZE"),
            "RESNET_WARMUP_EPOCHS": os.environ.get("RESNET_WARMUP_EPOCHS"),
            "USE_MULTIMODAL": os.environ.get("USE_MULTIMODAL"),
            "RESNET_LR": os.environ.get("RESNET_LR"),
            "RESNET_WEIGHT_DECAY": os.environ.get("RESNET_WEIGHT_DECAY"),
            "RESNET_DROPOUT": os.environ.get("RESNET_DROPOUT"),
            "RESNET_PATIENCE": os.environ.get("RESNET_PATIENCE"),
            "RESNET_CLASS_WEIGHTS": os.environ.get("RESNET_CLASS_WEIGHTS"),
        },
        "inputs": {
            "split_csv": str(split_csv.relative_to(REPO_ROOT)),
            "split_csv_sha256": _sha256_file(split_csv),
            "training_experiments": str(experiments_path.relative_to(REPO_ROOT)),
            "training_experiments_sha256": _sha256_file(experiments_path),
        },
        "outputs": {
            "metrics_json": {
                "path": "output/etapa2/metrics.json",
                "sha256": _sha256_file(ETAPA2_DIR / "metrics.json"),
            },
            "plots": {
                str(dst_curves.relative_to(REPO_ROOT)): _sha256_file(dst_curves),
                str(dst_cm.relative_to(REPO_ROOT)): _sha256_file(dst_cm),
            },
        },
    }
    _write_json(ETAPA2_DIR / "manifest.json", manifest)

    print("[PC2] Wrote:")
    print(f"- {ETAPA2_DIR / 'metrics.json'}")
    print(f"- {ETAPA2_DIR / 'manifest.json'}")
    print(f"- {dst_curves}")
    print(f"- {dst_cm}")


if __name__ == "__main__":
    main()
